#!/bin/bash
set -u
set -e
NAME="debian_sid_post_install"
DESCRIPTION="unstable/sid configuration"
GITHUB="https://github.com/vonbrownie"
SOURCE="${GITHUB}/linux-post-install/blob/master/debian_sid_post_install"
# Notes
# * Install Debian Wheezy Screenshot Tour
#   http://www.circuidipity.com/install-debian-wheezy-screenshot-tour.html

greeting() {
cat << _EOF_

$NAME - $DESCRIPTION

Howdy! Ideally this script is run following a fresh installation of
Debian GNU/Linux.

See: "Install Debian Wheezy Screenshot Tour"
http://www.circuidipity.com/install-debian-wheezy-screenshot-tour.html

This system will be configured to track Debian's sid/unstable branch
with the option of installing the lightweight Openbox window manager
+ extra apps suitable for a desktop environment.

This script should be run with ROOT privileges. Please check it before
use in a text editor and make any required modifications.

_EOF_
}

penguinista() {
cat << _EOF_

(O<
(/)_
_EOF_
}

test_root() {
if [[ $UID -ne 0 ]]
then
    printf "\n$( penguinista ) .: $NAME requires ROOT privileges to do its job.\n"
    exit 1
fi
}

test_connect() {
    :
}

test_condition() {
test_root
test_connect
}

invalid_reply() {
    :
}

invalid_reply_yn() {
    :
}

confirm_start() {
    :
}

apt_prefer() {
    :
}

apt_source() {
    :
}

apt_key() {
    :
}

apt_purge() {
    :
}

pkg_console() {
    :
}

pkg_desktop() {
    :
}

pkg_openbox() {
    :
}

pkg_theme() {
    :
}

pkg_dvd() {
    :
}

pkg_experiment() {
    :
}

pkg_non_deb() {
    :
}

config_desktop() {
    :
}

config_blacklist() {
    :
}

config_alternative() {
    :
}

config_group() {
    :
}

config_timezone() {
    :
}

au_revoir() {
clear
printf "$( penguinista ) .: All done!\n"
}

#: START
test_condition
greeting
#confirm_start

#: APT
#apt_prefer
#apt_source
#apt_key

#: CONFIGURE
#config_desktop
#config_blacklist
#config_alternative
#config_group
#config_timezone

#: FINISH
#apt_purge
#au_revoir
